ECommerce/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('demands.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
]

if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),]

demands/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.OrderList.as_view(), name='list'),
    path('details/<int:pk>', views.OrderDetails.as_view(), name='details'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('', views.ProductList.as_view(), name='list'),
    path('search/', views.Search.as_view(), name='search'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('addtocart/', views.AddToCart.as_view(), name='addcart'),
    path('removefromcart/', views.RemoveFromCart.as_view(), name='removecart'),
    path('cart/getcep/', views.get_cart_cep_price, name='cep_cart_price'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('checkout/getaddress/', views.get_checkoutaddress, name='getaddress'),
    path('category/<str:category>',
         views.ProductCategory.as_view(), name='category'),
    path('<slug>', views.ProductDetails.as_view(), name='detail'),

]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('address/', views.AddressList.as_view(), name='address'),
    path(
        'address/<int:pk>',
        views.AddressUpdate.as_view(), name='addressdetails'
    ),
    path('address/<int:pk>/delete', views.AddressDelete.as_view(), name='delete'),
    path(
        'address-create/',
        views.AddressCreate.as_view(), name='addresscreate'
    ),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path(
        'address/address/', views.cep_update, name='cepupdate'
    ),
    path(
        'address-create/address/', views.cep_update, name='cepupdate-newaddress'
    ),
]

demands/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings
from datetime import date
import os


class Demand(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    shipping_price = models.FloatField()
    total_w_shipping = models.FloatField()
    total_qty = models.PositiveIntegerField()
    creation_date = models.DateField(default=date.today)
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Approved'),
            ('C', 'Created'),
            ('D', 'Disapproved'),
            ('P', 'Pending'),
            ('S', 'Sent'),
            ('F', 'Finished'),
        ),
    )

    def __str__(self) -> str:
        return f'Order N. {self.pk}'


class ItemDemand(models.Model):
    order = models.ForeignKey(Demand, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promo_price = models.FloatField(default=0)
    quantity = models.PositiveIntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self) -> str:
        return f'Item from {self.order}'

    class Meta:
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'


class AddressDemand(models.Model):
    order = models.ForeignKey(Demand, on_delete=models.CASCADE)
    address_id = models.PositiveIntegerField()
    address = models.CharField(max_length=50)
    number = models.CharField(max_length=8, blank=True, null=True)
    complement = models.CharField(max_length=30, blank=True, null=True)
    city = models.CharField(max_length=30)
    cep = models.CharField(max_length=8)

    def __str__(self):
        return self.address

    class Meta:
        verbose_name = 'Address'
        verbose_name_plural = 'Addresses'

templates/partials/_cart.html
{% load static %}
{% load vnpfilters %}


{% for line in cart.values %}
<form action="{%url 'products:removecart'%}" method="get" name="delete-form">
    <input type="hidden" name="vid" value="{{line.variation_id}}">
    <div class="row shadow-all p-3 rounded-1 mb-3 mx-1 justify-content-center justify-content-lg-start">
        <div class="d-none d-sm-flex col-sm-4 col-lg-4 col-xl-3 p-4">
            <div>
                <a href="{% url 'products:detail' line.slug %}">
                    <img src="{% get_media_prefix %}{{ line.image }}" class="w-100 rounded-lg"
                        alt="{{ line.image.name }}" />
                </a>
            </div>
        </div>

        <div class="col-sm-8 col-xl-9 mb-4 mb-md-0 align-self-center">
            <a class="row text-dec" href="{% url 'products:detail' line.slug %}">
                <h5><strong>{{ line.product_name }}</strong></h5>
            </a>
            <div class="row justify-content-between">
                <div class="col-md-6 mb-4 mb-md-0 align-self-center">

                    {% if line.category == "C" %}
                    <p class="mb-0"><strong>Size: </strong>{{line.variation_name}}</p>
                    {% else %}
                    <p class="mb-0"><strong> Variation: </strong> {{line.variation_name}}</p>
                    {% endif %}

                    {% if line.promo_unit_price %}
                    <p><strong> Unit price: </strong> {{line.promo_unit_price|price_format}}</p>
                    {% else %}
                    <p><strong> Unit price: </strong> {{line.unit_price|price_format}}</p>
                    {% endif %}


                    <button type="button" class="btn main-color btn-sm hover-color" title="Move to the wish list">
                        <i class="fas fa-heart"></i>
                    </button>
                </div>

                <div class="col-md-6 align-self-end">
                    <div class="row justify-content-center justify-content-md-end">
                        <div class="col-4 col-lg-3 pr-0 pl-sm-5 p-md-0 mb-3 text-center text-md-left">
                            <h5 class="fw-normal mb-0" itemsQTY="{{line.quantity}}" name="item-qty">
                                {{line.quantity}}</h5>
                        </div>
                        <div class="col-6 col-md-10 col-lg-7 p-0 mb-4 mr-lg-1 text-center text-md-right">
                            {% if line.promo_quantitative_price %}
                            <h5 class="mb-0">{{line.promo_quantitative_price|price_format}}</h5>
                            {% else %}
                            <h5 class="mb-0">{{line.quantitative_price|price_format}}</h5>
                            {% endif %}
                        </div>
                        {% if not request.path == '/checkout/' %}
                        <select name="del-qty" id="delete-qty"
                            class="col-3 col-sm-2 col-md-6 col-lg-5 col-xl-4 form-control-sm mr-1 mw-50"></select>
                        <button type="button" class="col-2 col-md-5 col-xl-4 btn btn-danger mw-40"
                            name="button-delete-item" id="button-delete-item" title="Remove item">
                            <i class="fas fa-trash"></i>
                        </button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endfor %}

templates/partials/_footer.html
{% load static %}

<footer class=" main-color">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1 text-left">
                    <span class="align-middle p-1">Made with Django
                    </span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">By Alan Martins</span>
                </div>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'vendor/js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'vendor/js/popper.min.js' %}"></script>
<script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'vendor/js/all.js' %}"></script>
<script src="{% static 'vendor/js/scripts.js' %}"></script>
<script src="{% static 'vendor/js/index.js' %}"></script>

templates/partials/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}" />
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'vendor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'vendor/css/index.css' %}">

templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/_nav.html
{% load static %}
{% load vnpfilters %}
<nav class="nav-header main-color navbar-expand-lg px-2 shadow-all">
    <div class="nav-header-width">
        <div class="nav-header-flex">

            <a class="navbar-brand" href="{% url 'products:list' %}"> <img src="{% static 'VNP.png' %}"
                    alt="logo site image">
            </a>

            <div class="flex-search">
                <div class="d-flex" onclick="toggleSearch()">
                    <img data-src="//d2az8otjr0j19j.cloudfront.net/templates/001/078/806/twig/static/images/icon-search.png?84488646"
                        src="//d2az8otjr0j19j.cloudfront.net/templates/001/078/806/twig/static/images/icon-search.png?84488646"
                        alt class="img-fluid lazyloaded" width="24" height="24">
                    <span class="d-none d-md-block">Click here to search</span>
                </div>
                <form id="nav-search-form" class="row" method="get" action="{% url 'products:search' %}">
                    <div id="nav-search-div">
                        <img data-src="//d2az8otjr0j19j.cloudfront.net/templates/001/078/806/twig/static/images/icon-search.png?84488646"
                            src="//d2az8otjr0j19j.cloudfront.net/templates/001/078/806/twig/static/images/icon-search.png?84488646"
                            alt class="img-fluid lazyloaded" width="24" height="24">
                        <input name="term" id="nav-search-input" value="{{ request.GET.term }}" class="form-control"
                            type="search" placeholder="Type here what you are looking for" aria-label="Search">
                        <button id="nav-search-btn" class="btn btn-size btn-danger d-none ml-md-2 text-white"
                            type="submit">Search</button>
                    </div>
                </form>
            </div>
            <div class="d-flex flex-column align-items-center">
                <button class="btn btn-outline-danger btn-sm btn-size d-lg-none mb-2" type="button"
                    onclick="toggleMenu()">
                    <div class="bars">
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </button>
                <button id="toggleMenu" class="btn btn-outline-danger btn-sm text-white d-none d-lg-block mb-2"
                    type="button" onclick="toggleMenu()">Categories</button>

                <div class="profile-menu">
                    {% if request.session.cart %}
                    <a class="cart-draw" href="{% url 'products:cart' %}">
                        <strong>{{request.session.cart|cart_total_qty}}x</strong>
                        <span class="fas fa-shopping-cart"></span>
                    </a>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <div class="profile-btn" onmouseover="dropDown()" onmouseout="dropDown()">
                        <button class='btn btn-outline-danger btn-sm btn-size text-white d-none d-sm-block'
                            type="button">
                            Profile &#9662
                        </button>
                        <button class='btn btn-outline-danger btn-sm btn-size btn-sm-size text-white d-sm-none'
                            type="button">
                            <i class="fa fa-user"></i>
                        </button>
                        <div class="profile-intern-menu main-color" id="profileDropDown">
                            <a href="{% url 'orders:list' %}">My Orders</a>
                            <a href="{% url 'profiles:create' %}">Update Profile</a>
                            <a href="{% url 'profiles:address' %}">Update Address</a>
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'profiles:logout' %}">Logout</a>
                        </div>
                    </div>

                    {% else %}
                    <button id="nav-login"
                        class="btn btn-outline-danger btn-sm btn-size btn-sm-size text-white mr-lg-0 p-0" type="button">
                        <a href="{% url 'profiles:create' %}" class="justify-content-center">
                            <i class="fa fa-user"></i>
                            <span class="d-none d-lg-block ml-2">Login</span>
                        </a>
                    </button>
                    {% endif %}
                </div>

            </div>
            <nav id="menu" class="menu">
                <div class="close-menu" onclick="toggleMenu()"></div>
                <ul>
                    <li>
                        <a href="{% url 'products:list' %}">
                            Home
                        </a>
                    </li>
                    <li><a href="{% url 'products:category' 'T' %}">Technology</a></li>
                    <li><a href="{% url 'products:category' 'F' %}">Furnitures</a></li>
                    <li><a href="{% url 'products:category' 'C' %}">Clothes</a></li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li onmouseover="dropRight()" onmouseout="dropRight()">
                        <a href="#" role="button" data-toggle="dropdown">
                            Profile</a>
                        <div class="intern-menu second-color" id="navbarDropleft">
                            <a href="{% url 'orders:list' %}">My Orders</a>
                            <a href="{% url 'profiles:create' %}">Update Profile</a>
                            <a href="{% url 'profiles:address' %}">Update Address</a>
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'profiles:logout' %}">Logout</a>
                        </div>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'profiles:create' %}">
                            Login</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'products:cart' %}">
                            Cart
                        </a>
                    </li>
                </ul>
            </nav>


        </div>

    </div>
</nav>
<div class="block-outside" id="block-outside" onclick="toggleMenu()"></div>
<div class="block-outside" id="block-search" onclick="toggleSearch()"></div>

templates/partials/_order.html
{% load static %}
{% load vnpfilters %}
<div class="card rounded-lg shadow all text-color-two">
    <div class="card-header py-3">
        <h3>{{order}}</h3>
    </div>
    <div class="card-body">
        <div class="col">

            <div class="row">
                <div class="col mt-0 mt-sm-3">
                    <p class="text-muted mb-2">PRODUCTS</p>
                    <hr class="mt-0">
                </div>
            </div>

            <div class="col-10 col-md-12 card-body mx-auto pt-0">
                {% for line in order.itemdemand_set.all %}
                <div class="row p-3 my-3 rounded-lg shadow-all">
                    <div class="col-md-2 d-flex justify-content-center align-items-center px-0 pb-2 pb-md-0">
                        <div class="cart-img p-3">
                            <img src="{% get_media_prefix%}{{line.image}}" class="img-fluid rounded-lg"
                                alt="{{line.product}}">
                        </div>
                    </div>
                    <div class="col-md-3 text-center d-flex justify-content-center align-items-center">
                        <p class="text-muted mb-0">{{line.product}}</p>
                    </div>
                    <div class="col-md-3 text-center d-flex justify-content-center align-items-center">
                        <p class="text-muted mb-0 small">{{line.variation}}</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                        <p class="text-muted mb-0 small">Qty: {{line.quantity}}</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                        <p class="text-muted mb-0 small">
                            {% if line.promo_price %}
                            {{line.promo_price|price_format}}
                            {% else %}
                            {{line.price|price_format}}
                            {% endif %}
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class=" my-3">
                <span id="track_error" class="text-red"></span>
            </div>
            <div class="track" id="track">
                <div class="step" id="track_confirmed"> <span class="icon" title="Order confirmed"> <i
                            class="fa fa-check" id="track_confirmed_dissaproved"></i>
                    </span> <span class="text d-none d-sm-block" id="order_step">Order confirmed</span>
                </div>
                <div class="step" id="track_pending"> <span class="icon" title="Waiting for courier pickup"> <i
                            class="fa fa-user"></i>
                    </span> <span class="text d-none d-sm-block">
                        Waiting for courier pickup</span>
                </div>
                <div class="step" id="track_sent"> <span class="icon" title="On the way"> <i class="fa fa-truck"></i>
                    </span><span class="text d-none d-sm-block"> On the
                        way </span>
                </div>
                <div class="step" id="track_finished"> <span class="icon" title="Ready for pickup"> <i
                            class="fa fa-box"></i> </span> <span class="text d-none d-sm-block">Ready for
                        pickup</span>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col">
                    <p class="text-muted mb-2">ORDER DETAILS</p>
                    <hr class="mt-0">
                </div>
            </div>
            <div class="row">
                <div class="col-2 font-weight-bold mw-150">Order number:</div>
                <div class="col-5 col-sm-7 col-md-9 col-lg-4 pr-0 p-sm-0">{{order.id}}</div>
                <div class="col-2 font-weight-bold mw-150">Shipping price:</div>
                <div class="col-5 col-sm-7 col-md-9 col-lg-4 pr-0 p-sm-0">{{order.shipping_price|price_format}}</div>
                <div class="col-2 font-weight-bold mw-150">Total Items:</div>
                <div class="col-5 col-sm-7 col-md-9 col-lg-4 pr-0 p-sm-0">{{order.total_qty}}</div>
                <div class="col-2 font-weight-bold mw-150">Status:</div>
                <div class="col-5 col-sm-7 col-md-9 col-lg-4 pr-0 p-sm-0" id="order_status">{{order.get_status_display}}
                </div>
                <div class="col-2 font-weight-bold mw-150">Order date:</div>
                <div class="col-5 col-sm-7 col-md-9 col-lg-4 pr-0 p-sm-0">{{order.creation_date}}</div>

            </div>

            <div class="row mt-3">
                <div class="col">
                    <p class="text-muted mb-2">SHIPPING ADDRESS</p>
                    <hr class="mt-0">
                </div>
            </div>
            <div class="row">
                {% if address.complement %}
                <div class="col-1 font-weight-bold mw-110">Address:</div>
                <div class="col-7 pr-0 p-sm-0">{{address.address}}, n⁰ {{address.number}},
                    {{address.complement}}, {{address.city}}, {{address.cep}}</div>
                {% else %}
                <div class="col-1 font-weight-bold mw-110">Address:</div>
                <div class="col-7 pr-0 p-sm-0">{{address.address}}, n⁰ {{address.number}},
                    {{address.city}}, {{address.cep}}</div>
                {% endif %}
            </div>



        </div>
    </div>
    <div class="card-footer second-color py-3">
        <h5 class="d-flex align-items-center justify-content-end mb-0 pr-3">TOTAL
            PAID: <span class="h2 mb-0 ml-2">{{order.total_w_shipping|price_format}}</span></h5>
    </div>
</div>

templates/partials/_pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link second-color" href="?page=1{{additional_url_query}}">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link second-color"
                        href="?page={{ page_obj.previous_page_number }}{{additional_url_query}}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item">
                    <a class="page-link main-color" href="?page={{ num }}{{additional_url_query}}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <li class="page-item">
                    <a class="page-link second-color" href="?page={{ num }}{{additional_url_query}}">{{ num }}</a>
                    </li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link second-color"
                            href="?page={{ page_obj.next_page_number }}{{additional_url_query}}">&rsaquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link second-color"
                            href="?page={{ page_obj.paginator.num_pages }}{{additional_url_query}}">&raquo;</a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}