ECommerce/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('demands.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
]

if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),]

demands/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.OrderList.as_view(), name='list'),
    path('details/<int:pk>', views.OrderDetails.as_view(), name='details'),
]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('address/', views.AddressList.as_view(), name='address'),
    path(
        'address/<int:pk>',
        views.AddressUpdate.as_view(), name='addressdetails'
    ),
    path('address/<int:pk>/delete', views.AddressDelete.as_view(), name='delete'),
    path(
        'address-create/',
        views.AddressCreate.as_view(), name='addresscreate'
    ),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path(
        'address/address/', views.cep_update, name='cepupdate'
    ),
    path(
        'address-create/address/', views.cep_update, name='cepupdate-newaddress'
    ),
]

profiles/forms.py
from utils import addressgenerator
from django import forms
from django.contrib.auth.models import User
from datetime import date
from . import models
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Row, Column, Button


today = date.today()


class ProfileForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.DateInput(
        attrs={'type': 'date', 'max': today}), required=True, label='Birth Date')

    cpf = forms.CharField(
        max_length=11, help_text='CPF only numbers', label='CPF')

    class Meta:
        model = models.Profile
        fields = '__all__'
        exclude = ('user',)


class AddressForm(forms.ModelForm):
    class Meta:
        model = models.Address
        fields = '__all__'
        exclude = ('user',)

    address = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    number = forms.CharField(max_length=8, required=False)
    complement = forms.CharField(required=False)
    neighborhood = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    city = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={'readonly': 'readonly'}))
    state = forms.CharField(max_length=2, widget=forms.TextInput(
        attrs={'readonly': 'readonly'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(Fieldset(
            "",
            Row(
                Column('cep', css_class='col'),
                Column(Button(
                    'submit', 'Find CEP', css_class='btn btn-danger text-white col-md-auto mb-button-cep btn-md', onclick='getCEP()',
                )),
                css_class=' justify-content-between'
            ),
            'address',
            'number',
            'complement',
            'neighborhood',
            'city',
            'state',
        ),
            Submit('submit', 'Update',
                   css_class='btn btn-danger text-white btn-block btn-lg')
        )

    field_order = ['cep',]


class CEPForm(forms.ModelForm):
    class Meta:
        model = models.Address
        fields = '__all__'
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_show_labels = False


class UserForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address')
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
    )

    password_confirm = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Password Confirmation'
    )

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.user = user

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'password', 'password_confirm', 'email')

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        user_data = cleaned.get('username')
        email_data = cleaned.get('email')
        password_data = cleaned.get('password')
        password_confirm_data = cleaned.get('password_confirm')

        user_db = User.objects.filter(username=user_data).first()
        email_db = User.objects.filter(email=email_data).first()

        error_msg_user_exists = 'User already exists'
        error_msg_email_exists = 'E-mail already exists'
        error_msg_required_field = 'This field is required.'
        error_msg_password_short = 'Password needs at least 6 characters'
        error_msg_password_match = 'Password confirmation do not match'

        if self.user:
            if user_db:
                if user_data == str(self.user):
                    pass
                else:
                    validation_error_msgs['username'] = error_msg_user_exists

            if not email_data:
                validation_error_msgs['email'] = error_msg_required_field

            if email_db:
                if email_data == str(self.user.email):
                    pass
                else:
                    validation_error_msgs['email'] = error_msg_email_exists

            if password_data:
                if password_data != password_confirm_data:
                    validation_error_msgs['password_confirm'] = error_msg_password_match

                if len(password_data) < 6:
                    validation_error_msgs['password'] = error_msg_password_short

        else:
            if user_db:
                validation_error_msgs['username'] = error_msg_user_exists

            if not email_data:
                validation_error_msgs['email'] = error_msg_required_field

            if email_db:
                validation_error_msgs['email'] = error_msg_email_exists

            if not password_data:
                validation_error_msgs['password'] = error_msg_required_field

            elif len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_short

            if password_data != password_confirm_data:
                validation_error_msgs['password_confirm'] = error_msg_password_match

        if validation_error_msgs:
            raise (forms.ValidationError(validation_error_msgs))

profiles/views.py
from crispy_forms.templatetags.crispy_forms_filters import as_crispy_field
from django.http import JsonResponse
from utils import addressgenerator
from .forms import AddressForm
from django.views.generic import ListView, UpdateView
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView
from django.views import View
from django.http import HttpResponseNotFound, HttpResponse
from . import models, forms
import copy


class BaseProfile(View):
    template_name = 'profiles/create.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.cart = copy.deepcopy(self.request.session.get('cart', {}))

        self.profile = None
        self.address = None

        if self.request.user.is_authenticated:
            self.template_name = 'profiles/update.html'

            self.profile = models.Profile.objects.filter(
                user=self.request.user).first()
            self.address = models.Address.objects.filter(
                user=self.profile).all()

            self.address_id = kwargs.get("pk", None)
            self.address_filter = self.address.filter(
                id=self.address_id).first()

            self.context = {
                'userform': forms.UserForm(data=self.request.POST or None, user=self.request.user, instance=self.request.user,),
                'profileform': forms.ProfileForm(data=self.request.POST or None, instance=self.profile),
                'addressform': forms.AddressForm(data=self.request.POST or None),
                'addresses': self.address,
                'addressdetails': forms.AddressForm(
                    data=self.request.POST or None, instance=self.address_filter),
            }

            self.addressdetails = self.context['addressdetails']

        else:
            self.context = {
                'userform': forms.UserForm(data=self.request.POST or None),
                'profileform': forms.ProfileForm(data=self.request.POST or None),
                'addressform': forms.AddressForm(data=self.request.POST or None),
            }

        self.userform = self.context['userform']
        self.profileform = self.context['profileform']
        self.addressform = self.context['addressform']

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, self.context)


class Create(BaseProfile):
    def post(self, *args, **kwargs):

        if (not self.userform.is_valid() or not self.profileform.is_valid()) and not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'There are errors in the register form. Check if all fields have been filled correctly.'
            )
            return render(self.request, 'profiles/register.html', self.context)

        if not self.userform.is_valid() or not self.profileform.is_valid():
            messages.error(
                self.request,
                'There are errors in the register form. Check if all fields have been filled correctly.'
            )
            return render(self.request, self.template_name, self.context)

        username = self.userform.cleaned_data.get('username')
        password = self.userform.cleaned_data.get('password')
        email = self.userform.cleaned_data.get('email')
        first_name = self.userform.cleaned_data.get('first_name')
        last_name = self.userform.cleaned_data.get('last_name')

        cpf_data = self.profileform.cleaned_data.get('cpf')
        cpf_db = models.Profile.objects.filter(cpf=cpf_data).first()

        if self.request.user.is_authenticated:
            user = get_object_or_404(User, username=self.request.user.username)
            user.username = username

            if password:
                user.set_password(password)

            user.email = email
            user.first_name = first_name
            user.last_name = last_name
            user.save()

            if cpf_db:
                if str(cpf_db) != str(self.profile.user):
                    messages.error(
                        self.request, 'CPF is already registered.')
                    return redirect('profiles:create')

            if not self.profile:
                self.profileform.cleaned_data['user'] = user
                profile = models.Profile(**self.profileform.cleaned_data)
                profile.save()
            else:
                profile = self.profileform.save(commit=False)
                profile.user = user
                profile.save()

            messages.info(
                self.request,
                'Your profile has been successfully updated'
            )

            if self.request.session.get('cart'):
                return redirect('products:checkout')
            return self.render

        else:
            if cpf_db:
                messages.error(
                    self.request, 'The CPF is already registered.')
                return render(self.request, self.template_name, self.context)

            user = self.userform.save(commit=False)
            user.set_password(password)
            user.save()

            profile = self.profileform.save(commit=False)
            profile.user = user
            profile.save()

            messages.info(
                self.request,
                'Your profile has been successfully created'
            )

        if password:
            authentica = authenticate(
                self.request,
                username=username,
                password=password
            )

            if authentica:
                login(self.request, user=user)
                messages.info(
                    self.request,
                    'Please add your first address to your profile.'
                )
                return redirect('profiles:address')
        # TODO: em vez de redirecionar p um monte de lugar, criar um template do dashboard com os links?
        self.request.session['cart'] = self.cart
        self.request.session.save()

        self.render = render(self.request, self.template_name, self.context)

        if self.request.session['cart']:
            return redirect('products:cart')
        return self.render


class DispatchLoginRequired(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('profiles:create')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        profile = models.Profile.objects.filter(
            user=self.request.user).first()
        qs = qs.filter(user=profile)
        return qs


class AddressUpdate(DispatchLoginRequired, BaseProfile):
    address_template_name = 'profiles/updateaddress.html'

    def get(self, *args, **kwargs):
        if not self.address_filter:
            return HttpResponseNotFound()

        return render(self.request, self.address_template_name, self.context)

    def post(self, request, *args, **kwargs):

        if not self.addressdetails.is_valid():
            messages.error(
                self.request,
                'There are errors in the register form. Check if all fields have been filled correctly.'
            )
            return render(self.request, self.address_template_name, self.context)

        self.address_data = self.addressdetails.cleaned_data

        if self.request.user.is_authenticated:

            if not self.address:
                self.addressdetails.cleaned_data['user'] = self.profile
                address = models.Address(**self.addressdetails.cleaned_data)
                address.save()
            else:
                address_exists = self.address.filter(
                    cep__iexact=self.address_data['cep'], number__iexact=self.address_data['number']
                ).first()

                if address_exists:
                    if self.address_data['complement'] != address_exists.complement:
                        address = self.addressdetails.save(commit=False)
                        address.user = self.profile
                        address.save()

                        messages.info(
                            self.request,
                            'Your address has been successfully updated'
                        )
                    else:
                        messages.warning(
                            self.request,
                            'This address already exists in your profile.'
                        )

                        return redirect('profiles:addressdetails', self.address_id)
                else:
                    address = self.addressdetails.save(commit=False)
                    address.user = self.profile
                    address.save()

                    messages.info(
                        self.request,
                        'Your address has been successfully updated'
                    )

            if self.request.session.get('cart'):
                return redirect('products:checkout')

            return redirect('profiles:address')

        else:
            return redirect('profiles:addresscreate')


def cep_update(request, *args, **kwargs):
    if request.method == 'GET':
        form = forms.AddressForm(request.GET)

        cep = request.GET['cep']

        if cep == "":
            return JsonResponse({"cep": "EMPTY CEP"})

        cep_refresher = addressgenerator.address(cep)

        if cep_refresher is None:
            return HttpResponse(as_crispy_field(form['cep']))

        changes = {
            'address': cep_refresher['logradouro'],
            'neighborhood': cep_refresher['bairro'],
            'city': cep_refresher['cidade'],
            'state': cep_refresher['uf'],
        }

profiles/templates/profiles/address.html
{% extends 'base.html' %}


{% block title %}Addresses from {{ user }} | {% endblock %}

{% block content %}

<div class="row text-color-two">
    <div class="col">
        <h3 class="mb-4">Adresses from {{user}}</h3>
        <p>Here are all your addresses created</p>

        <div class="table-responsive">
            <table class="table table-striped table-hover address-table">
                <thead>
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">CEP</th>
                        <th scope="col">Address</th>
                        <th scope="col">Number</th>
                        <th scope="col">Neighborhood</th>
                        <th scope="col">City</th>
                        <th scope="col">State</th>
                        <th scope="col"></th>
                    </tr>
                </thead>

                <tbody>
                    {% for address in addresses %}
                    <tr class="text-center">
                        <td class="button-table-start">
                            <form action="{% url 'profiles:delete' address.id %}" method="get">
                                <button type="submit" class="btn btn-danger text-white shadow-all">
                                    Delete <input type="hidden" name="pk" value={{address.id}}>
                                </button>
                            </form>
                        </td>
                        <td scope="row">{{address.cep}}</td>
                        <td>{{address.address}}</td>
                        <td>{{address.number}}</td>
                        <td>{{address.neighborhood}}</td>
                        <td>{{address.city}}</td>
                        <td>{{address.state}}</td>
                        <td class="button-table-end">
                            <form action="{% url 'profiles:addressdetails' address.id %}" method="get">
                                <button type="submit" class="btn main-color text-white shadow-all">
                                    Edit <i class="fas fa-search-plus ml-2"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
        <div class="row">
            <div class="col ">
                <button type="button" class='btn new-address btn-danger mt-3 float-right shadow-all'><a
                        href="{% url 'profiles:addresscreate' %}">+ New
                        Address</a></button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

profiles/templates/profiles/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Profile | {% endblock %}

{% block content %}

<div class="row text-color-two">

  {% if not request.user.is_authenticated %}
  <div id="login-form" class="col-md-10 col-lg-8 m-auto">
    <h3>Login</h3>

    <form method='POST' action="{% url 'profiles:login' %}">
      {% csrf_token %}

      <div class="form-outline mb-3 mt-4">
        <label class="form-label" for="InputUser1">Username</label>
        <input type="text" name='username' id="InputUser1" class="form-control" />
      </div>

      <div class="form-outline mb-4">
        <label class="form-label" for="InputPassword1">Password</label>
        <input type="password" name='password' id="InputPassword1" class="form-control" />
      </div>

      <div class="row mb-4">
        <div class="col d-flex justify-content-center">

          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="RememberUser1" checked />
            <label class="form-check-label" for="RememberUser1"> Remember me </label>
          </div>

        </div>
      </div>

      <button type="submit" class="btn btn-danger btn-block mb-4 text-white">Login</button>

      <div class="text-center">
        <p>Not a member? <a href="#!" onclick="clickRegister()">Register</a></p>
      </div>
    </form>
  </div>
  {% endif %}

  <div id="register-form" class="col-md-10 col-lg-8 m-auto d-none">

    {% block updatetitle %}
    <h3>Register</h3>
    {% endblock updatetitle %}

    <form class='mt-4' id="update-cep" action="" method="post">
      {% block updateform %}

      {% csrf_token %}
      {{ userform|crispy }}
      {{ profileform|crispy }}

      {% endblock updateform %}

      {% block updatebutton %}
      <div class="row">
        <div class="col">
          <button type="submit" class='btn btn-danger btn-block text-white mb-4'>Register</button>
        </div>
      </div>
      <div class="text-center">
        <p>Already a member? <a href="#!" onclick="clickLogin()">Login</a></p>
      </div>

      {% endblock updatebutton %}
    </form>
  </div>
</div>

{% endblock %}

profiles/templates/profiles/newaddress.html
{% extends 'profiles/create.html' %}
{% load crispy_forms_tags %}


{% block title %}New Address from {{ user }} | {% endblock %}

{% block updatetitle %}
<h2>Create Address</h2>
<h4>Use this form to create a new address</h4>
{% endblock updatetitle %}

{% block updateform %}

{% csrf_token %}
{% crispy addressform %}


{% endblock updateform %}

{% block updatebutton %}{% endblock updatebutton %}

profiles/templates/profiles/register.html
{% extends 'profiles/create.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row text-color-two">

    <div id="register-form" class="col-lg-6 m-auto">

        {% block updatetitle %}
        <h3>Register</h3>
        {% endblock updatetitle %}

        <form class='mt-4' id="update-cep" action="" method="post">
            {% block updateform %}

            {% csrf_token %}
            {{ userform|crispy }}
            {{ profileform|crispy }}

            {% endblock updateform %}

            {% block updatebutton %}
            <div class="row">
                <div class="col">
                    <button type="submit" class='btn btn-danger btn-block text-white btn-lg'>Send</button>
                </div>
            </div>
            {% endblock updatebutton %}
        </form>
    </div>
</div>

{% endblock %}

profiles/templates/profiles/update.html
{% extends 'profiles/create.html' %}

{% block title %}Update Profile from {{ user }} | {% endblock %}

{% block updatetitle %}
<h3>Update Profile</h3>
<p>Use this form to Update your profile.</p>
{% endblock updatetitle %}

{% block updatebutton %}
<div class="row">
    <div class="col">
        <button type="submit" class='btn btn-danger btn-block text-white shadow-all'>Update</button>
    </div>
</div>
{% endblock updatebutton %}

profiles/templates/profiles/updateaddress.html
{% extends 'profiles/create.html' %}
{% load crispy_forms_tags %}


{% block title %}Update Addresses from {{ user }} | {% endblock %}

{% block updatetitle %}
<h2>Update Address</h2>
{% endblock updatetitle %}

{% block updateform %}

{% csrf_token %}
{% crispy addressdetails %}


{% endblock updateform %}

{% block updatebutton %}{% endblock updatebutton %}