ECommerce/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('order/', include('demands.urls')),

    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
]

if settings.ADMIN_ENABLED:
    urlpatterns += [path('admin/', admin.site.urls),]

demands/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('saveorder/', views.SaveOrder.as_view(), name='saveorder'),
    path('list/', views.OrderList.as_view(), name='list'),
    path('details/<int:pk>', views.OrderDetails.as_view(), name='details'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('', views.ProductList.as_view(), name='list'),
    path('search/', views.Search.as_view(), name='search'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('addtocart/', views.AddToCart.as_view(), name='addcart'),
    path('removefromcart/', views.RemoveFromCart.as_view(), name='removecart'),
    path('cart/getcep/', views.get_cart_cep_price, name='cep_cart_price'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('checkout/getaddress/', views.get_checkoutaddress, name='getaddress'),
    path('category/<str:category>',
         views.ProductCategory.as_view(), name='category'),
    path('<slug>', views.ProductDetails.as_view(), name='detail'),

]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'

urlpatterns = [
    path('', views.Create.as_view(), name='create'),
    path('address/', views.AddressList.as_view(), name='address'),
    path(
        'address/<int:pk>',
        views.AddressUpdate.as_view(), name='addressdetails'
    ),
    path('address/<int:pk>/delete', views.AddressDelete.as_view(), name='delete'),
    path(
        'address-create/',
        views.AddressCreate.as_view(), name='addresscreate'
    ),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path(
        'address/address/', views.cep_update, name='cepupdate'
    ),
    path(
        'address-create/address/', views.cep_update, name='cepupdate-newaddress'
    ),
]

products/models.py
from django.db import models
from PIL import Image
from django.conf import settings
from django.utils.text import slugify
from utils import utils
from django.core.validators import MinValueValidator
import os


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='name')
    summary = models.TextField(max_length=255)
    description = models.TextField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    mrkt_price = models.FloatField(verbose_name='marketing price')
    promo_mrkt_price = models.FloatField(
        default=0,
        verbose_name='promotional marketing price'
    )
    category = models.CharField(
        default='T',
        max_length=1,
        choices=(
            ('T', 'Technology'),
            ('C', 'Clothes'),
            ('F', 'Furniture'),
        ))
    var_type = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variable'),
            ('S', 'Simple'),
        )
    )

    def get_formatted_price(self):
        return utils.price_format(self.mrkt_price)
    get_formatted_price.short_description = 'Marketing Price'

    def get_formatted_promo_price(self):
        return utils.price_format(self.promo_mrkt_price)
    get_formatted_promo_price.short_description = 'Promotional Price'

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}'
            self.slug = slug
        super().save(*args, **kwargs)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to=r'product_img/%Y/%m/%d',
        blank=True,
        null=True, unique=True
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            self.resize_image(self.image.name, 800)

    @staticmethod
    def resize_image(img_name, new_width):
        img_path = os.path.join(settings.MEDIA_ROOT, img_name)
        img = Image.open(img_path)
        width, height = img.size
        new_height = round((new_width * height) / width)

        if width <= new_width:
            img.close()
            return

        new_img = img.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_path,
            optimize=True,
            quality=60,
        )
        new_img.close()


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True,
                            null=True, verbose_name='Variation name')
    price = models.FloatField()
    promo_price = models.FloatField(default=0)
    stock = models.PositiveIntegerField(validators=[MinValueValidator(1)])

    def __str__(self):
        return self.name or self.product.name

products/forms.py
from django.forms.models import BaseInlineFormSet


class RequiredVariation(BaseInlineFormSet):
    def _construct_form(self, i, **kwargs):
        form = super(RequiredVariation, self)._construct_form(i, **kwargs)
        form.empty_permitted = False
        return form

products/views.py
from utils.utils import price_format, cart_totals
from utils import shippingcalculator
from utils import addressgenerator
from django.http import JsonResponse
from profiles.models import Address, Profile
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse
from django.views import View
from django.contrib import messages
from django.db.models import Q
from . import models
from profiles.forms import CEPForm


class ProductList(ListView):
    model = models.Product
    template_name = 'products/list.html'
    context_object_name = 'products'
    paginate_by = 6
    ordering = ['-id']


class Search(ProductList):
    def get_queryset(self, *args, **kwargs):
        self.term = self.request.GET.get('term')
        qs = super().get_queryset(*args, **kwargs)

        if not self.term:
            return qs

        qs = qs.filter(
            Q(name__icontains=self.term) |
            Q(summary__icontains=self.term) |
            Q(description__icontains=self.term)
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.term

        if not search_term:
            return ctx

        ctx.update({
            "additional_url_query": f'&term={search_term}',
        })

        return ctx


class ProductCategory(ProductList):
    def get_queryset(self, *args, **kwargs):
        category = self.kwargs.get('category', None)
        qs = super().get_queryset(*args, **kwargs)

        if not category:
            return qs

        qs = qs.filter(category__iexact=category)

        return qs


class ProductDetails(DetailView):
    model = models.Product
    template_name = 'products/detail.html'
    context_object_name = 'product'
    slug_url_kwarg = 'slug'


class AddToCart(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('products:list')
        )
        variation_id = self.request.GET.get('vid')
        variation_quantity_add = self.request.GET.get('qty')

        if not variation_id:
            messages.error(
                self.request,
                'Product does not exist'
            )
            return redirect(http_referer)

        variation = get_object_or_404(models.Variation, id=variation_id)
        stock_variation = variation.stock
        product = variation.product

        product_id = product.id
        product_name = product.name
        variation_name = variation.name or ''
        unit_price = variation.price
        promo_unit_price = variation.promo_price
        slug = product.slug
        category = product.category
        images = models.ProductImage.objects.filter(
            product_id=product_id).first()
        image = images.image

        if image:
            image = image.name
        else:
            image = ''

        if variation.stock < 1:
            messages.error(
                self.request,
                'Product Unavailable'
            )
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            self.request.session['cart'] = {}
            self.request.session.save()

        cart = self.request.session['cart']

        error_msg_stock = f'Insufficient stock for "{product_name} {variation.name}". There is only {stock_variation} in stock.'

        if variation_id in cart:
            cart_quantity = cart[variation_id]['quantity']
            cart_quantity += int(variation_quantity_add)

            if stock_variation < cart_quantity:
                messages.warning(
                    self.request,
                    error_msg_stock
                )
                return redirect(http_referer)

            cart[variation_id]['quantity'] = cart_quantity
            cart[variation_id]['quantitative_price'] = unit_price * cart_quantity
            cart[variation_id]['promo_quantitative_price'] = promo_unit_price * cart_quantity

        else:
            if stock_variation < int(variation_quantity_add):
                messages.warning(
                    self.request,
                    error_msg_stock
                )
                return redirect(http_referer)

            cart[variation_id] = {
                'product_id': product_id,
                'product_name': product_name,
                'category': category,
                'variation_name': variation_name,
                'variation_id': variation_id,
                'unit_price': unit_price,
                'promo_unit_price': promo_unit_price,
                'quantitative_price': unit_price * int(variation_quantity_add),
                'promo_quantitative_price': promo_unit_price * int(variation_quantity_add),
                'quantity': int(variation_quantity_add),
                'slug': slug,
                'image': image,
            }

        self.request.session.save()

        messages.success(
            self.request,
            f'Added {variation_quantity_add}x "{product.name} {variation.name}" to cart.'
        )

        return redirect(http_referer)


class RemoveFromCart(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('products:cart')
        )
        variation_id = self.request.GET.get('vid')

        if not variation_id:
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            return redirect(http_referer)

        if variation_id not in self.request.session['cart']:
            return redirect(http_referer)

        delete_qty = self.request.GET.get('del-qty')
        cart = self.request.session['cart'][variation_id]

        cart['quantity'] -= int(delete_qty)
        cart['quantitative_price'] = cart['unit_price'] * cart['quantity']
        cart['promo_quantitative_price'] = cart['promo_unit_price'] * \
            cart['quantity']
        if cart['quantity'] < 1:
            del self.request.session['cart'][variation_id]

        messages.info(
            self.request,
            f'{delete_qty}x {cart["product_name"]} {cart["variation_name"]} removed from cart.'
        )

        self.request.session.save()

        return redirect(http_referer)


class Cart(View):
    def get(self, *args, **kwargs):
        context = {
            'cart': self.request.session.get('cart', {}),
            'address': CEPForm,
        }

        return render(self.request, 'products/cart.html', context)


class Checkout(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.info(
                self.request,
                'Login or create an account to proceed with the order'
            )
            return redirect('profiles:create')

        if not self.request.session['cart']:
            return redirect('products:cart')

        self.profile = Profile.objects.filter(
            user=self.request.user).first()
        self.address = Address.objects.filter(
            user=self.profile).all()

        if not self.profile:
            messages.error(
                self.request, 'Complete your profile and address before proceeding with your order')
            return redirect('profiles:create')
        if not self.address:
            messages.error(
                self.request, 'Create a new address before proceeding with your order')
            return redirect('profiles:address')

        instance_address = []
        for i in range(0, self.address.count()):
            instance_address.append(self.address[i])
        first_address = instance_address[0]

        context = {
            'user': self.request.user,
            'cart': self.request.session['cart'],
            'addresses': self.address,
            'first_address': first_address,
        }

        return render(self.request, 'products/checkout.html', context)


def get_checkoutaddress(request, *args, **kwargs):
    if request.user.is_authenticated:
        if request.method == 'GET':
            request.profile = Profile.objects.filter(
                user=request.user).first()
            request.address = Address.objects.filter(
                user=request.profile).all()

            address_id = request.GET['inputSelect']

            address = request.address.filter(id=address_id).first()

            shipping_price = shippingcalculator.calculator(address.cep)
            shipping_price_formatted = price_format(shipping_price)

            cart = cart_totals(request.session['cart'])
            sum_cart = shipping_price + cart
            sum_cart_formatted = price_format(sum_cart)

            shipping = {
                'address': address.address,
                'complement': address.complement,
                'city': address.city,
                'cep': address.cep,
                'number': address.number,
                'neighborhood': address.neighborhood,
                'state': address.state,
                'shipping_price_formatted': shipping_price_formatted,
                'cart_total': sum_cart_formatted,
            }

            return JsonResponse(shipping)


def get_cart_cep_price(request, *args, **kwargs):
    if request.method == 'GET':
        cep_number = request.GET['inputSelect']
        cart = cart_totals(request.session['cart'])
        cart_only = price_format(cart)

        if not cep_number:
            return JsonResponse({
                "price": "false",
                "cart_only": cart_only,
            })

        valid_cep = addressgenerator.address(cep_number)
        if not valid_cep:
            return JsonResponse({
                "price": "false",
                "cart_only": cart_only,
            })

        shipping_price = shippingcalculator.calculator(cep_number)

products/templates/products/detail.html
{% extends 'base.html' %}
{% load vnpfilters %}

{% block title %}{{product.name}} | {% endblock %}

{% block content %}

<div class="card shadow-all rounded-lg p-3">
    <div class="col-lg-12 text-color-two text-justify">
        <div class="row justify-content-center">
            {% if product.productimage_set.all %}
            <div class="card-body col-lg-5 text-center">
                <div class="row mx-auto p-3" id="img-div-all">
                    <div class="col-lg-12">
                        <div id="carouselDetailImg{{ product.id }}" class="carousel slide" data-ride="carousel"
                            data-interval="false">
                            <div class="carousel-inner rounded-lg">
                                {% for image in product.productimage_set.all %}
                                {% if forloop.first %}
                                <div class="carousel-item active">
                                    <img class="w-100 rounded-lg" src="{{ image.image.url }}" alt="{{ product.name }} ">
                                </div>
                                {% else %}
                                <div class="carousel-item">
                                    <img class="w-100 rounded-lg" src="{{ image.image.url }}" alt="{{ product.name }}">
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            {% if product.productimage_set.all|length > 1 %}
                            <a class="carousel-control-prev" href="#carouselDetailImg{{ product.id }}" role="button"
                                data-slide="prev">
                                <span><i class="fa fa-angle-left fa-2x text-danger" aria-hidden="true"></i></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselDetailImg{{ product.id }}" role="button"
                                data-slide="next">
                                <span><i class="fa fa-angle-right fa-2x text-danger" aria-hidden="true"></i></span>
                                <span class="sr-only">Next</span>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row no-gutters justify-content-center" id="prev-img-detail">
                    {% for image in product.productimage_set.all %}
                    <div><img class="rounded-lg" src="{{image.image.url}}" alt="{{product.name}}">
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            <div class="col-lg-7">
                <div class="card-body mt-4 mt-lg-0 text-space">
                    <h2 class="text-center text-lg-left">{{product.name}}</h2>
                    <p class="lead">{{ product.summary|linebreaks }}</p>
                    <p>

                        {% if product.promo_mrkt_price %}
                        <span id="variation-price-promo" class="font-weight-bold product-price">
                            {{product.promo_mrkt_price|price_format}}
                        </span>

                        <span id="variation-price" class="product-old-price">
                            {{product.mrkt_price|price_format}}
                        </span>

                        {% else %}
                        <span id="variation-price-promo" class="font-weight-bold product-price">
                            {{product.mrkt_price|price_format}}
                        </span>

                        <span id="variation-price-none" class="font-weight-bold product-price">
                        </span>
                        {% endif %}
                    </p>

                    <form action="{% url 'products:addcart' %}" id="form-add-to-cart">
                        <div class="form-group ">
                            <select id="select-variations" name="vid" class="form-control">

                                {% for variation in product.variation_set.all %}
                                {% if not variation.stock %}

                                <option data-price-promo="{{ variation.price|price_format }}" value="{{ variation.id }}"
                                    id="insufficient-stock" stock="{{variation.stock}}">
                                    {{variation}}
                                </option>

                                {% elif variation.promo_price %}

                                <option data-price="{{ variation.price|price_format }}"
                                    data-price-promo="{{ variation.promo_price|price_format }}"
                                    value="{{ variation.id }}" stock="{{variation.stock}}">
                                    {{variation}}
                                </option>

                                {% else %}

                                <option data-price-promo="{{ variation.price|price_format }}" value="{{ variation.id }}"
                                    stock="{{variation.stock}}">
                                    {{variation}}
                                </option>

                                {% endif %}
                                {%endfor%}
                            </select>
                            <span id="product-not-avaiable"></span>
                            <div class="row mt-3 justify-content-end" id="qty_avaiable">
                                <p class="col text-right">Select Quantity:</p>
                                <select class="form-control col-1 mw-75 mr-3" id="select-quantities" name="qty">
                                </select>
                            </div>
                        </div>

                        <div class="text-left ml-auto p-0">
                            <button type="submit" class="btn btn-danger btn-lg btn-block text-white shadow-all"
                                id="add-cart-button">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Add to Cart
                            </button>
                        </div>

                    </form>


                </div>
            </div>
        </div>


        <div class="row card-body">
            <div class="col-lg-12">
                <div class="mt-3 mt-lg-5 mb-5 text-space">
                    <h2 class="text-center d-none d-lg-block mb-3">{{ product.name }}</h2>
                    {{ product.description|linebreaks }}
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

products/templates/products/list.html
{% extends 'base.html' %}
{% load vnpfilters %}

{% block content %}

<div class="row justify-content-center">

    {% for product in products %}
    <div class="col-12 col-md-6 col-lg-4 mb-4 max-w-card">
        <div class="card text-color-two h-100 shadow-all">

            {% if product.productimage_set.all %}
            <div id="carouselControl{{ product.id }}" class="card-img-block d-flex pt-3 px-5 carousel slide"
                data-ride="carousel">
                <div class="carousel-inner my-auto rounded-lg">
                    {% for image in product.productimage_set.all %}
                    {% if forloop.first %}
                    <div class="carousel-item active">
                        <a href="{% url 'products:detail' product.slug %}">
                            <img class="card-img-top card-img-size d-block rounded-lg" src="{{ image.image.url }}"
                                alt="{{ product.name }}">
                        </a>
                    </div>
                    {% else %}
                    <div class="carousel-item">
                        <a href="{% url 'products:detail' product.slug %}">
                            <img class="card-img-top card-img-size d-block rounded-lg" src="{{ image.image.url }}"
                                alt="{{ product.name }}">
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% if product.productimage_set.all|length > 1 %}
                <a class="carousel-control-prev" href="#carouselControl{{ product.id }}" role="button"
                    data-slide="prev">
                    <span><i class="fa fa-angle-left fa-2x text-danger" aria-hidden="true"></i></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselControl{{ product.id }}" role="button"
                    data-slide="next">
                    <span><i class="fa fa-angle-right fa-2x text-danger" aria-hidden="true"></i></span>
                    <span class="sr-only">Next</span>
                </a>
                {% endif %}
            </div>
            {% endif %}

            <div class="card-body text-justify">
                <h5 class="card-title text-center">{{product.name}}</h5>
                {% if product.category != "C" %}
                <p class="card-text">{{product.summary}}</p>
                {% endif %}
            </div>
            <div class="container product-price-block text-center">

                {% if product.promo_mrkt_price %}
                <span class="product-price">
                    {{product.promo_mrkt_price|price_format}}
                </span>
                <span class="product-old-price text-muted">
                    {{product.mrkt_price|price_format}}
                </span>
                {% else %}
                <span class="product-price">
                    {{product.mrkt_price|price_format}}
                </span>
                {% endif %}

            </div>
            <div class="card-footer text-center">
                <a href="{% url 'products:detail' product.slug %}"
                    class="btn btn-danger text-white btn-sm m-1 btn-block shadow-all">
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    Buy
                </a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>


{% endblock %}